TITLE="Beej's Guide to Using UNIX"
SUBTITLE=""
AUTHOR='Brian “Beej Jorgensen” Hall'
VERSION_DATE="v0.0.1, Copyright © March 15, 2025"

GUIDE_ID=bguunix
BGBSPD_BUILD_DIR?=../../bgbspd

#WEB_IMAGES=$(wildcard img_*.svg img_*.png)

include $(BGBSPD_BUILD_DIR)/source.make
